USE test;

-- ADD PRIMARY KEY
ALTER TABLE pets
ADD PRIMARY KEY (id);

-- ADD FOREIGN KEY
ALTER TABLE pets
ADD CONSTRAINT FK_PersonID
FOREIGN KEY (owner_id) REFERENCES people(id);

-- ADD COLUMN
ALTER TABLE people
ADD COLUMN email VARCHAR(30);

-- ADD UNIQUE CONSTRSINT
ALTER TABLE people
ADD CONSTRAINT u_email UNIQUE (email);

-- RENAME COLUMN
ALTER TABLE pets
CHANGE `name` `first_name` VARCHAR(20)

-- CHANGE DATATYPE
ALTER TABLE addresses
MODIFY postcode CHAR(7);
